name: "Semantic Pull Requests"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - "main"

jobs:
  main:
    name: semantic-pull-request
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
